apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-serverless
spec:
  channel: "4.7"
  name: serverless-operator
  source: redhat-stage-operators
  sourceNamespace: openshift-marketplace
